name 'RailsApp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures RailsApp'
long_description 'Installs/Configures RailsApp'
version '0.1.0'
