development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mysql-railsSQL
  pool: 5
  username: root
  password: railspassword
  host:
  port:

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mysql-railsSQL
  pool: 5
  username: root
  password: railspassword
  host:
  port:

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mysql-railsSQL
  pool: 5
  username: root
  password: railspassword
  host:
  port:
