name 'MySQLServer'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures MySQLServer'
long_description 'Installs/Configures MySQLServer'
version '0.1.0'
depends 'mysql', '~> 6.0'
